export const GITHUB_URL = 'https://github.com/keston-4'
export const INSTAGRAM_URL = ''
export const LINKEDIN_URL = 'https://linkedin.com/in/kurt-weston/'
export const TWITTER_URL = ''
export const EMAIL = ''
export const PHONE = ''
export const ADDRESS = ''
export const RESUME_URL = ''
